### ISSUE TITLE
Translate Homepage to Russian language

### ISSUE THREAD

**Issue by domnantas** [LRMD/ARManual#12]
# The problem
The homepage is the first step to translating ARManual to another language

# Requirements
- [x] Create `ARManual/ru/` directory
- [x] Copy content from `ARManual/README.md` (or `ARManual/lt/README.md`) to `ARManual/ru/README.md`
- [x] Translate `ARManual/ru/README.md` to Russian language
- [x] Translate `ARManual/.vuepress/config.js` settings
	- [x] Add `/ru/` to `locales`

**Comment by korstan** [comment]
Hello, @domnantas ! I would like to help your project with Russian translations: this issue, #14 and in the future (if there will be any). I'm a native Russian speaker with a bit of knowledge in radio technologies.
Can you assign this issue to me?

**Comment by domnantas** [comment]
Sure!
