### ISSUE TITLE
Translate Homepage to Spanish language

### ISSUE THREAD

**Issue by domnantas** [LRMD/ARManual#13]
# The problem
The homepage is the first step to translating ARManual to another language

# Requirements
- [x] Create `ARManual/es/` directory
- [x] Copy content from `ARManual/README.md` (or `ARManual/lt/README.md`) to `ARManual/es/README.md`
- [x] Translate `ARManual/es/README.md` to Spanish language
- [x] Translate `ARManual/.vuepress/config.js` settings
	- [x] Add `/es/` to `locales`
	- [x] Add `/es/` to `plugins['@vuepress/pwa'].updatePopup`
	- [x] Add `/es/` to `themeConfig.locales`

**Comment by FernandoRoldan93** [comment]
Hi! I can translate the README.md to Spanish. I will also try to translate the .js settings file but my js skills are very limited so forgive me if my syntax is not correct 😢

**Comment by domnantas** [comment]
Closed by https://github.com/LRMD/ARManual/pull/17

**Comment by domnantas** [comment]
Deployed live: https://armanual.org/es/
