### ISSUE TITLE
Translate Phonetic alphabet to Russian language

### ISSUE THREAD

**Issue by domnantas** [LRMD/ARManual#14]
# The problem
The phonetic alphabet page is very simple but useful. It should be available in the Russian language.

# Requirements
- [x] Copy `ARManual/phonetic-alphabet/README.md` to `ARManual/ru/phonetic-alphabet/README.md`
- [x] Translate the table headings
- [x] Add additional column for Russian pronounciations of phonetic alphabet
- [ ] Add additional table of Cyrillic phonetic alphabed

**Comment by korstan** [comment]
Hello, @domnantas ! I can help with this one. Described my skills in comments section of another issue about Russian translation.
You can assign this one to me too, Russian phonetic alphabet exists and I can add pronunciations using it.
