### ISSUE TITLE
Translate Phonetic alphabet to Spanish language

### ISSUE THREAD

**Issue by domnantas** [LRMD/ARManual#15]
# The problem
The phonetic alphabet page is very simple but useful. It should be available in the Spanish language.

# Requirements
- [x] Copy `ARManual/phonetic-alphabet/README.md` to `ARManual/es/phonetic-alphabet/README.md`
- [x] Translate the table headings
- [ ] Add additional column for Spanish phonetic alphabet (if that exists)

**Comment by alanverdugo** [comment]
Hi @domnantas , I am a native Spanish speaker and I could help with this issue. Could you assign the issue to me, please?

**Comment by domnantas** [comment]
Sure!

**Comment by alanverdugo** [comment]
Hi @domnantas ! Thank you for accepting my PR! :)

Could you please label this issue as `hacktoberfest-accepted` so it counts towards my goal?
Thank you!
