### ISSUE TITLE
Translate Q code to Russian language

### ISSUE THREAD

**Issue by domnantas** [LRMD/ARManual#41]
# The problem
The [Q Code page](https://armanual.org/q-code/) should be translated to Russian language

# Requirements
- [ ] Copy `ARManual/q-code/README.md` to `ARManual/ru/q-code/README.md`
- [ ] Translate the table headings
- [ ] Translate table content
- [ ] Change the link from `/q-code/` to `/ru/q-code` [here](https://github.com/LRMD/ARManual/blob/6fcdfeaa3251b4cf8854adb725e2daa8f1b8bab1/ARManual/.vuepress/config.ts#L206)

**Comment by SvA1** [comment]
Hey, I'd like to help with the translation, could you assign this issue to me?

**Comment by domnantas** [comment]
Absolutely, thanks!
